name: Build and Run Spring Boot App

on:
  workflow_dispatch:   # ✅ manual trigger button
  schedule:
    - cron: '* 2-10 * * 1-5'
    - cron: '30-32 15 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (skip tests)
        run: mvn -B package -DskipTests

      - name: Run Spring Boot App
        run: mvn spring-boot:run -DskipTests

