name: Run Java App

on:
  push:
    branches: [ "main" ]   # run on pushes to main branch

jobs:
  run-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile All Java files
        run: javac -d out $(find src -name "*.java")

      - name: Run Java
        run: java -cp out start.Bonito.Main

